version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4890:8080"
    volumes:
      - ./server.log:/server.log           # Map server.log to the host
      - ./Error.log:/Error.log             # Map Error.log to the host
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7                         # Changed from redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

volumes:
  redis_data: